# Generated by Django 4.2 on 2026-01-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='delete_password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
